version: '2.0'

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: tunji
      POSTGRES_PASSWORD: tunji
      POSTGRES_DB: exampledb
  adminer:
    image: adminer
    restart: always 
    depends_on: 
      - database
    ports:
      - "8080:8080"
