# Generated by Django 5.0.4 on 2024-04-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendordisc',
            table='vendors',
        ),
    ]
